name: buscotest
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - augustus=3.5.0=pl5321h2f37ef0_5
  - bamtools=2.5.2=h447d7a5_5
  - bbmap=39.13=h92e07a1_0
  - biopython=1.84=py310h936d840_0
  - blast=2.16.0=h461d46c_3
  - boost-cpp=1.85.0=h07eb623_2
  - brotli-python=1.1.0=py310h53e7c6a_2
  - busco=5.8.0=pyhdfd78af_0
  - bwidget=1.9.14=h694c41f_1
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.3=hf13058a_1
  - ca-certificates=2024.12.14=h8857fd0_0
  - cairo=1.18.0=h99e66fa_0
  - cctools_osx-64=986=h58a35ae_0
  - cdbtools=0.99=hdf58011_10
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py310hfce808e_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - clang=18.1.7=default_ha3b9224_0
  - clang-18=18.1.7=default_h4c8afb6_0
  - clang_impl_osx-64=18.1.7=h671483d_16
  - clang_osx-64=18.1.7=hb91bd55_16
  - clangxx=18.1.7=default_ha3b9224_0
  - clangxx_impl_osx-64=18.1.7=h5c1d95e_16
  - clangxx_osx-64=18.1.7=hb91bd55_16
  - clustalw=2.1=h85dcccf_10
  - compiler-rt=18.1.7=h734a56e_0
  - compiler-rt_osx-64=18.1.7=h7312ed1_0
  - curl=8.8.0=hea67d85_1
  - dendropy=5.0.1=pyhdfd78af_0
  - diamond=2.1.10=hd576cc4_2
  - dnspython=2.7.0=pyhff2d567_0
  - entrez-direct=22.4=h193322a_0
  - expat=2.6.4=h240833e_0
  - fasttree=2.1.11=h26a06ae_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=hbcb3906_0
  - gawk=5.3.1=h0631170_0
  - gettext=0.22.5=hdfe23c8_3
  - gettext-tools=0.22.5=hdfe23c8_3
  - gfortran_impl_osx-64=12.3.0=hc328e78_3
  - gfortran_osx-64=12.3.0=h18f7dce_1
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.13=h73e2aa4_1003
  - gsl=2.7=h93259b0_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=h053f038_0
  - hmmer=3.4=h4a92bd6_2
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.21=hec81eee_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.10=pyhd8ed1ab_0
  - isl=0.26=imath32_h2e86a7b_101
  - k8=0.2.5=hdf58011_4
  - krb5=1.21.3=h37d8d59_0
  - ld64_osx-64=711=had5d0d3_0
  - lerc=4.0.0=hb486fe8_0
  - libasprintf=0.22.5=hdfe23c8_3
  - libasprintf-devel=0.22.5=hdfe23c8_3
  - libblas=3.9.0=25_osx64_openblas
  - libboost=1.85.0=h739af76_2
  - libboost-devel=1.85.0=h2b186f8_2
  - libboost-headers=1.85.0=h694c41f_2
  - libcblas=3.9.0=25_osx64_openblas
  - libclang-cpp18.1=18.1.7=default_h4c8afb6_0
  - libcurl=8.8.0=hf9fcc65_1
  - libcxx=19.1.4=hf95d169_0
  - libdeflate=1.20=h49d49c5_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.2=h0d85af4_5
  - libgettextpo=0.22.5=hdfe23c8_3
  - libgettextpo-devel=0.22.5=hdfe23c8_3
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran-devel_osx-64=12.3.0=h0b6f5ec_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.80.2=h0f68cf7_0
  - libhwloc=2.11.2=default_hb6fbd3b_1000
  - libiconv=1.17=hd75f5a5_2
  - libidn2=2.3.7=h10d778d_0
  - libintl=0.22.5=hdfe23c8_3
  - libintl-devel=0.22.5=hdfe23c8_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=25_osx64_openblas
  - libllvm18=18.1.7=hd5e122f_0
  - libnghttp2=1.58.0=h64cf6d3_1
  - libopenblas=0.3.28=openmp_hbf64a52_1
  - libopenssl-static=3.4.0=hd471939_0
  - libpng=1.6.43=h92b6c6a_0
  - libsqlite=3.46.0=h1b8f9f3_0
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.6.0=h129831d_3
  - libunistring=0.9.10=h0d85af4_0
  - libuuid=2.38.1=hb7f2c08_0
  - libwebp-base=1.4.0=h10d778d_0
  - libxml2=2.12.7=h3e169fe_1
  - libzlib=1.2.13=h87427d6_6
  - llvm-openmp=19.1.4=ha54dae1_0
  - llvm-tools=18.1.7=hd5e122f_0
  - lp_solve=5.5.2.11=h10d778d_0
  - mafft=7.526=hfdf4475_0
  - make=4.4.1=h00291cd_2
  - metaeuk=7.bba0d80=pl5321h7efec2e_1
  - metis=5.1.0=h3023b02_1007
  - minimap2=2.28=h10309d6_3
  - miniprot=0.13=h10309d6_1
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - muscle=3.8.1551=hb280591_6
  - mysql-connector-c=6.1.11=h89ed7f3_1008
  - ncbi-vdb=3.1.1=hac4f329_2
  - ncurses=6.5=hf036a51_1
  - numpy=2.1.3=py310hdf3e1fd_0
  - openjdk=22.0.1=h2d185b6_0
  - openssl=3.4.0=hd471939_0
  - pandas=2.2.3=py310ha53a654_1
  - pango=1.54.0=h115fe74_1
  - pasta=1.9.2=py310h8cda308_1
  - pcre=8.45=he49afe7_0
  - pcre2=10.43=h0ad2156_0
  - perl=5.32.1=7_h10d778d_perl5
  - perl-app-cpanminus=1.7048=pl5321hd8ed1ab_0
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-method-modifiers=2.13=pl5321h694c41f_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321haeee4d3_0
  - perl-compress-raw-zlib=2.202=pl5321h0aa47d9_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-dbi=1.643=pl5321h6e16a3a_1
  - perl-encode=3.21=pl5321h00291cd_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-inc-latest=0.500=pl5321h694c41f_0
  - perl-io-compress=2.201=pl5321h4a92bd6_3
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321hac4f329_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h8af04d4_3
  - perl-module-build=0.4234=pl5321h694c41f_0
  - perl-moo=2.005004=pl5321h694c41f_0
  - perl-parallel-forkmanager=2.03=pl5321hdfd78af_0
  - perl-parent=0.242=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h6e16a3a_1
  - perl-role-tiny=2.002004=pl5321h694c41f_0
  - perl-scalar-list-utils=1.68=pl5321h6e16a3a_0
  - perl-storable=3.15=pl5321h00291cd_0
  - perl-sub-quote=2.006006=pl5321h694c41f_0
  - perl-test-fatal=0.016=pl5321h694c41f_0
  - perl-try-tiny=0.31=pl5321h694c41f_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-yaml=1.30=pl5321hdfd78af_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.4=h73e2aa4_0
  - prank=170427=h85dcccf_0
  - prodigal=2.6.3=h8af04d4_9
  - pycparser=2.22=pyhd8ed1ab_0
  - pymongo=4.10.1=py310h53e7c6a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=h00d2728_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - r-base=4.4.0=ha82e53a_1
  - r-cli=3.6.3=r44h25d921d_1
  - r-colorspace=2.1_1=r44h6b9d099_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44h6b9d099_3
  - r-fansi=1.0.6=r44h6b9d099_1
  - r-farver=2.1.2=r44h25d921d_1
  - r-ggplot2=3.5.1=r44hc72bb7e_1
  - r-glue=1.8.0=r44h199b6f9_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-isoband=0.2.7=r44h25d921d_3
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_6=r44h6b9d099_1
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44h6b9d099_3
  - r-mass=7.3_60.0.1=r44h6b9d099_1
  - r-matrix=1.6_5=r44h9cf22e7_1
  - r-mgcv=1.9_1=r44h374a70c_1
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_165=r44h9612530_1
  - r-pillar=1.9.0=r44hc72bb7e_2
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-r6=2.5.1=r44hc72bb7e_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rlang=1.1.4=r44h25d921d_1
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-tibble=3.2.1=r44h6b9d099_3
  - r-utf8=1.2.4=r44h6b9d099_1
  - r-vctrs=0.6.5=r44h25d921d_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - raxml=8.2.13=h8af04d4_2
  - readline=8.2=h9e318b2_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rpsbproc=0.5.0=h43736c0_1
  - samtools=1.21=h94387ee_0
  - sepp=4.5.5=py310h527b516_0
  - setuptools=75.6.0=pyhff2d567_1
  - sigtool=0.1.3=h88f4db0_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sqlite=3.46.0=h28673e1_0
  - suitesparse=5.10.1=h4bf45ed_3
  - tapi=1100.0.11=h9ce4665_0
  - tar=1.34=hcb2f6ea_1
  - tbb=2022.0.0=h0ec6371_0
  - tk=8.6.13=h1abcd95_1
  - tktable=2.10=hba9d6f1_6
  - tzdata=2024b=hc8b5060_0
  - ucsc-fatotwobit=472=h1b9a4eb_0
  - ucsc-twobitinfo=472=h52ff7b8_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wget=1.21.4=hca547e6_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - zlib=1.2.13=h87427d6_6
  - zstandard=0.23.0=py310h41d873f_1
  - zstd=1.5.6=h915ae27_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/buscotest
